# Generated by Django 2.2b1 on 2019-05-18 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('int1_percentage', models.FloatField(default=0)),
                ('int2_percentage', models.FloatField(default=0)),
                ('ass1_percentage', models.FloatField(default=0)),
                ('ass2_percentage', models.FloatField(default=0)),
                ('ass3_percentage', models.FloatField(default=0)),
                ('quiz1_percentage', models.FloatField(default=0)),
                ('quiz2_percentage', models.FloatField(default=0)),
                ('quiz3_percentage', models.FloatField(default=0)),
                ('sessional_pecentage', models.FloatField(default=0)),
                ('SGPA', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('int1_maxMarks', models.FloatField(default=0)),
                ('int1_secMarks', models.FloatField(default=0)),
                ('int2_maxMarks', models.FloatField(default=0)),
                ('int2_secMarks', models.FloatField(default=0)),
                ('ass1_maxMarks', models.FloatField(default=0)),
                ('ass1_secMarks', models.FloatField(default=0)),
                ('ass2_maxMarks', models.FloatField(default=0)),
                ('ass2_secMarks', models.FloatField(default=0)),
                ('ass3_maxMarks', models.FloatField(default=0)),
                ('ass3_secMarks', models.FloatField(default=0)),
                ('quiz1_maxMarks', models.FloatField(default=0)),
                ('quiz1_secMarks', models.FloatField(default=0)),
                ('quiz2_maxMarks', models.FloatField(default=0)),
                ('quiz2_secMarks', models.FloatField(default=0)),
                ('quiz3_maxMarks', models.FloatField(default=0)),
                ('quiz3_secMarks', models.FloatField(default=0)),
                ('sessional_maxMarks', models.FloatField(default=0)),
                ('sessional_secMarks', models.FloatField(default=0)),
                ('External_grade', models.CharField(default='-', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hall_ticket', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('current_branch', models.CharField(max_length=50)),
                ('proctor_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
